Part3 task2
alexleskov/TestGuru pull request #2
Opened 2019-02-03 16:12 UTC by alexleskov

2019-02-04 15:25 UTC, iBublik requested changes

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203145531_create_tests.rb
> +      t.integer :caregory_id
Для полей-связок рекомендуется сразу добавлять индекс и внешний ключ. Тут будет удобно создавать поле через [`t.references`](http://devdocs.io/rails~5.2/activerecord/connectionadapters/table#method-i-references) - он сразу создает индекс, можно указать опцию для создания внешнего ключа

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203145531_create_tests.rb
> +      t.integer :caregory_id
Только учти, что для корректного создания внешнего ключа таблица, на которую он ссылается, должна уже присутствовать в базе. Т.е. нельзя добавить внешний ключ к таблице категорий, пока сама таблица категорий не создана

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203145531_create_tests.rb
> +      t.integer :caregory_id
Актуально и для других таблиц

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203151804_add_test_title_null_constraint.rb
> +  	change_column_null(:tests, :title, false)
Внезапно таб вместо пробелов

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203151804_add_test_title_null_constraint.rb
> +  	change_column_null(:tests, :title, false)
Все однотипные миграции можно в одну объединить, чтоб не плодить миграции

2019-02-04 15:25 UTC, iBublik commented on db/migrate/20190203145917_create_answers.rb
> +      t.string :result
А что это? В таблицы представлены вариант ответов, а не ответы пользователя. Так что нужна пометка правильный это ответ или нет, а вот это поле лишнее

2019-02-04 16:27 UTC, alexleskov commented on db/migrate/20190203145917_create_answers.rb
> +      t.string :result
В result, имелось ввиду хранить статус ответа: pending, accept, decline

2019-02-04 16:33 UTC, alexleskov commented on db/migrate/20190203145917_create_answers.rb
> +      t.string :result
Да, что-то увлекся

2019-02-06 16:15 UTC, iBublik commented on db/migrate/20190204214544_add_null_constraint_for_tables_columns.rb
> +  	change_column_null(:tests, :title, false)
табы

2019-02-06 16:15 UTC, iBublik commented on db/migrate/20190204214714_add_default_values_for_columns_in_tables.rb
> +  	change_column_default(:tests, :level, 1)
😢

2019-02-06 16:15 UTC, iBublik commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
Вот это лучше в инишлайзер, а тут теряется

2019-02-06 16:15 UTC, iBublik commented on db/migrate/20190205194326_add_references_in_tables.rb
> +  	remove_column(:answers, :question_id, :integer)
Странная миграция получилась. Поля-то можно было не удалять, а просто добавить в ним индекс и внешний ключ

2019-02-06 16:15 UTC, iBublik commented on db/schema.rb
> +    t.integer "question_id"
Ответ без вопроса вряд ли имеет смысл

2019-02-06 16:15 UTC, iBublik commented on db/schema.rb
> +    t.integer "test_id"
Как и вопрос без теста

2019-02-06 16:54 UTC, alexleskov commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
Немного запутался.
Ты имеешь ввиду убрать в отдельный инишалайзер это?
Как здесь было: https://github.com/alexleskov/testguru/blob/150be079cf7a9ae05e4ecbef47474232b5875209/config/initializers/application_version.rb ?

Ну только без путс

2019-02-06 16:59 UTC, alexleskov commented on db/migrate/20190205194326_add_references_in_tables.rb
> +  	remove_column(:answers, :question_id, :integer)
Миграция ошибку выдавала, что поле test_id уже создано, когда t.reference пытался провернуть

2019-02-06 17:08 UTC, alexleskov commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
Или def initialize ; end )))

2019-02-06 17:10 UTC, alexleskov commented on db/schema.rb
> +    t.integer "test_id"
Может ты имел ввиду здесь вопрос без ответа?

2019-02-06 17:26 UTC, iBublik commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
Да, в отдельный файл-инишлайзер, только чтоб константа была объявлена в неймспейсе приложения. Если помнишь, в Ruby можно "перекотрывать" любой класс и докидывать в него метод/константы.

2019-02-06 17:27 UTC, iBublik commented on db/migrate/20190205194326_add_references_in_tables.rb
> +  	remove_column(:answers, :question_id, :integer)
`t.reference` используют для создания нового поля. У тебя оно уже существует, тебе надо было просто добавить индекс и внешний ключ

2019-02-06 17:27 UTC, iBublik commented on db/schema.rb
> +    t.integer "test_id"
Нет, тут же ссылка на тест. А вопрос без теста существовать не может

2019-02-09 14:24 UTC, merged