part4-task1 19.02.19
alexleskov/TestGuru pull request #3
Opened 2019-02-19 20:14 UTC by alexleskov

2019-02-20 15:48 UTC, iBublik requested changes

2019-02-20 15:48 UTC, iBublik commented on app/models/test.rb
> +  has_many :users, through: :test_stats
С ассоциациями ты поспешил, это тема следующего урока. Да и не используешь их никак

2019-02-20 15:48 UTC, iBublik commented on app/models/test.rb
> +    tests_by_category = Test.order(id: :desc).where("category_id = ?", category_id)
Реализация не очень эффективна - ты делаешь сначала запрос на категорию, потом на тесты. Можно все сделать одним запросом (вспомни как в задании по SQL мы получалис названия тестов и категорий)
Так же всегда предпочтительно использовать хэш вместо строк в запросах -  `where(category_id: category_id)`. Они проще читаются и изменяются

2019-02-20 15:48 UTC, iBublik commented on app/models/test.rb
> +    tests_by_category = Test.order(id: :desc).where("category_id = ?", category_id)
Сортировку надо сделать по названию теста

2019-02-20 15:48 UTC, iBublik commented on app/models/test.rb
> +    tests_by_category.each { |test| tests << test.title }
Ты изобрел `map` :)
А вообще можно эффективнее сделать - вместо того чтоб грузить в память AR объекты, сразу грузи массив. Поищи в доках, для этого есть метод

2019-02-20 15:48 UTC, iBublik commented on app/models/user.rb
> +    self.tests.where(level: value)
Можно без `self`
И тут важно понимать какой запрос делает ассоциация. Если понимаешь - ок, если нет - надо отказаться от ассоциации и сделать вручную

2019-02-20 15:48 UTC, iBublik commented on db/migrate/20190217201108_fix_column_name.rb
> +  	rename_column :tests, :caregory_id, :category_id
Снова таб вместо пробела

2019-02-20 15:48 UTC, iBublik commented on db/migrate/20190218184530_create_test_stats.rb
> +      t.boolean :success_status, default: false, null: false
Не рекомендую тащить это из teachbase :) не самое удачное решение

2019-02-20 15:48 UTC, iBublik commented on db/seeds.rb
> +categories = Category.create([{ title: 'Rails'}, { title: 'HTML'}, { title: 'PHP'}, { title: 'OOP'}])
Используй метод `create!` - он бросит исключение, если запись не создалась. Так сразу увидишь ошибку и будешь искать проблему в сидах.

2019-02-20 17:04 UTC, alexleskov commented on app/models/user.rb
> +    self.tests.where(level: value)
Вопрос тогда, чтобы понять, верно ли я рассуждаю)

Вот у меня добавлены ассоциации - я даю понять модели Юзер, что у него есть связь с моделью Статистики тестов и самими Тестами, через Статистики тестов. Причем один Юзер может иметь сразу несколько таких.

Изначально, у меня Юзер вообще не знает ни о каких Тестах и Статистиках тестов - у него есть методы только с его именем и ролью в системе.
Засчет этих ассоциаций я могу создать эту связь между Юзером и этими моделями Тест, Статистика теста.
Чтобы через Юзера я мог легко найти его тесты и стату тестов.

И как раз поэтому я могу вызвать на Юзере метод tests.

Это верно? :)

И к строке #3 вопрос:
TaskStats я использую, чтобы через ассоциацию я мог найти Тесты пользователя. Типо ТаскСтат та сущность, которая хранит в себе и id юзера и id теста.
Или я ошибаюсь?

2019-02-21 06:06 UTC, iBublik commented on app/models/user.rb
> +    self.tests.where(level: value)
Да, все верно. Но вообще я говорил про то, какой SQL запрос используется под капотом. Сможешь его составить вручную?

2019-02-21 06:13 UTC, alexleskov commented on app/models/user.rb
> +    self.tests.where(level: value)
Ага, понял, да. Это чисто для понимания спросил :) спасибо

2019-02-25 07:22 UTC, iBublik commented on app/models/test.rb
> +    Test.order(title: :desc).where(category_id: Category.where(title: value)).pluck(:title)
Ок, так тоже можно, но и "ручной" joins возможен - посмотри последний пример https://devdocs.io/rails~5.2/activerecord/querymethods#method-i-joins

2019-02-25 07:22 UTC, iBublik commented on app/models/user.rb
> +    Test.find(tests_ids)
Здесь можно было поступить как с категориями - `Test.where(id: TastStat...select(:test_id))`. Ну либо через joins. Будет 1 запрос, а не 2

2019-02-25 07:22 UTC, iBublik commented on db/seeds.rb
> +tests = Test.create!([{ title: 'Base in Rails', category_id: 1, level: 3 },
Нельзя жестко указывать id. Такой сид файл может создать неверные связи, если ты накатываешь его на существующую базу (там id могут быть заняты или вовсе отсутствовать). Используй результат метода `create!`, ты же не зря его в переменную пишешь

2019-02-25 18:40 UTC, alexleskov commented on app/models/test.rb
> +    Test.order(title: :desc).where(category_id: Category.where(title: value)).pluck(:title)
Я так решил не делать, из-за того, что там строкой задаётся запрос. А вообще, на будущее.
Там где можно использовать хэш - лучше используем хэш, а если что-то кастомное надо - то строкой запрос?

2019-02-26 04:39 UTC, iBublik commented on app/models/test.rb
> +                                         AND categories.title = '#{value}'").pluck(:title)
Условие на title перенеси в where. В joins нельзя использовать параметры, а просто вставлять значение "как есть" крайне небезопасно, это чревато sql инъекциями

2019-02-26 04:39 UTC, iBublik commented on app/models/user.rb
> +                AND test_stats.user_id = '#{id}' AND tests.level = '#{value}'")
Аналогично, условия на id и level перенеси в where.

2019-02-26 07:13 UTC, alexleskov commented on app/models/test.rb
> +                                         AND categories.title = '#{value}'").pluck(:title)
Пробовал изначально через "?" подставлять, но что-то не хотело. Попробую сегодня

2019-10-08 14:43 UTC, merged